version: '3'

services:
    leaderboard-api:
        build: .
        container_name: leaderboard-api        
        ports:
            - '3000:3000'
        networks: 
            - leaderboard-network

networks: 
    leaderboard-network:
        driver: bridge